addons:
  artifacts:
    debug: true
    paths: [libs.zip, build.zip, testbuild.zip]
    target_paths: d092b22d-29fc-494e-840f-cb3ca3143620
after_success: [./df-build.sh]
deploy:
  true: {tags: true}
  api_key: $API_KEY
  file: target/stashNotifier.hpi
  provider: releases
  skip_cleanup: true
language: java
# Modified by Insights Service at 2016-03-13 08:36:19.834636
