addons:
  artifacts:
    debug: true
    paths: [libs.zip, build.zip, testbuild.zip]
    target_paths: 9cf60cce-3849-4e96-be40-7363e5e9d4f8
after_success: [./df-build.sh]
deploy:
  true: {tags: true}
  api_key: $API_KEY
  file: target/stashNotifier.hpi
  provider: releases
  skip_cleanup: true
language: java
# Modified by Insights Service at 2016-03-14 19:29:59.384913
